### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by hardillb** [International/node-red-wfwatch#1]
Any chance you could rename this to comply with Node-RED naming guidelines?

As mentioned at the end of this page http://nodered.org/docs/creating-nodes/packaging

3rd party names should start _node-red-contrib-_ to distinguish them from core nodes.

Thanks

**Comment by International** [comment]
Sure thing! Will do so right away, thanks!

**Comment by International** [comment]
I've renamed the repo, and unpublished the previous package from npm. Please let me know if everything looks good to you, and then I can republish to npm. Thanks!

**Comment by hardillb** [comment]
Yeah, that looks better. Thanks.

Just curious, any reason why you didn't see if there was a fix for the existing node that could have been contributed back rather than publish a new one?

**Comment by International** [comment]
I checked the code for the node, and I got the same behaviour running it directly in node.js. Figured it must have been something related to `fs.notify` but I didn't look very much into it. Plus, I've never created a node before, so I figured the experience would be good for me.
